export const SET_LATEST_NEWS = 'SET-LATEST-NEWS';
export const SET_POPULAR_NEWS = 'SET-POPULAR-NEWS';
export const SET_LATEST_NEWS_ERROR = 'SET-LATEST-NEWS-ERROR';
export const SET_POPULAR_NEWS_ERROR = 'SET-POPULAR-NEWS-ERROR';
export const SET_LOADING_DATA = 'SET-LOADING-DATA';
